# The diets for each race. Each race can only eat what's listed.
diet:
  human:
    - ALL
  vampire:
    - NONE
  werewolf:
    - PORKCHOP
    - COOKED_PORKCHOP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - RABBIT
    - COOKED_RABBIT
    - RABBIT_STEW
    - MUTTON
    - COOKED_MUTTON
    - COOKED_COD
    - COOKED_SALMON