name: HeavenRPG
version: '${project.version}'
main: com.github.rfsmassacre.heavenrpg.HeavenRPG
api-version: '1.21'
author: "RFSMassacre"
depend:
  - HeavenLibrary
commands:
  heavenrpg:
    usage: "/heavenrpg"
  keybind:
    usage: "/keybind"